<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>02 Filter Product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>89bbf8d9-b648-4bd5-a8e5-b35d53d52303</testSuiteGuid>
   <testCaseLink>
      <guid>ccb9bf7c-2994-4cc8-b2be-f4e0ed9586a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/03 Filter Product Name Z - A</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69166811-54a6-4892-847b-82e629897206</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a82b68bd-762b-4d88-86e2-7a5a48e20c5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7023898e-7b3c-4e32-b4a3-5ee114c24458</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/04 Filter Product Name A - Z</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c95deb62-be84-4509-884e-646b3d23d077</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29040f76-6634-4b22-9f29-2e94d755aaae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bcded57-d933-48f8-a9c0-69ea9e6fddf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/05 Filter Product Price Low to High</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91abb09a-a32e-4754-b39a-8ed537147e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8002899-20d4-49d1-892d-e67bead45958</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ed17f0b-7bbf-41b1-9f7d-e9210ea3d0e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/06 Filter Product Price High to Low</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bcae985-b7d5-42f8-90d6-428487f24f8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>790b0f1e-d6b1-47f9-be8a-b529e346de08</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
